# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: ../../boletinTema7/boletinTema7Tarea1
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django-base-boletin-daniel
    container_name: django-base-pro_local_postgres_boletin
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - djangobasepro_boletin_data:/var/lib/postgresql/data
      #- djangobasepro_tutorial_backups:/backups
    ports:
      - 5432:5432

volumes:
  djangobasepro_boletin_data:
  #djangobasepro_tutorial_backups:


